// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBlLRKur7cJl0YatyB542Nz2lLPdCCIZMc',
//     appId: '1:494491220231:web:45ea034c5201a34623eda2',
//     messagingSenderId: '494491220231',
//     projectId: 'worker-ai-app',
//     authDomain: 'worker-ai-app.firebaseapp.com',
//     storageBucket: 'worker-ai-app.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAapjmWD9JLTLCgkPnYbszl6utUA8m2aQY',
//     appId: '1:494491220231:android:f550986dc7448ce923eda2',
//     messagingSenderId: '494491220231',
//     projectId: 'worker-ai-app',
//     storageBucket: 'worker-ai-app.firebasestorage.app',
//   );
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDLbk53VzyJG-ttVx0og2WG0izAv5Y3a8k',
//     appId: '1:494491220231:ios:ae29eee0c6971bfd23eda2',
//     messagingSenderId: '494491220231',
//     projectId: 'worker-ai-app',
//     storageBucket: 'worker-ai-app.firebasestorage.app',
//     iosBundleId: 'com.example.vehicleAiTest',
//   );
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDLbk53VzyJG-ttVx0og2WG0izAv5Y3a8k',
//     appId: '1:494491220231:ios:ae29eee0c6971bfd23eda2',
//     messagingSenderId: '494491220231',
//     projectId: 'worker-ai-app',
//     storageBucket: 'worker-ai-app.firebasestorage.app',
//     iosBundleId: 'com.example.vehicleAiTest',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBlLRKur7cJl0YatyB542Nz2lLPdCCIZMc',
//     appId: '1:494491220231:web:e0863dc27c038a5823eda2',
//     messagingSenderId: '494491220231',
//     projectId: 'worker-ai-app',
//     authDomain: 'worker-ai-app.firebaseapp.com',
//     storageBucket: 'worker-ai-app.firebasestorage.app',
//   );
// }
